---
- Infraestrutura:
    - Portainer:
        href: https://localhost:9443
        description: Gerenciamento de containers Docker
        icon: portainer.png
        server: my-docker
        container: portainer

    - RustDesk:
        href: http://100.122.61.34:21114
        description: Acesso remoto ao PC
        icon: rustdesk.png

    - Tailscale:
        href: https://login.tailscale.com/admin/machines
        description: Rede privada VPN
        icon: tailscale.png

- Inteligência Artificial:
    - Ollama API:
        href: http://100.122.61.34:443
        description: Servidor local de IA
        icon: ollama.png

- HomeLab:
    - Docker Desktop:
        href: https://localhost:9443
        description: Administração dos containers
        icon: docker.png